version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.11.0

workflows:
  build_push:
    jobs:
      - build
      - approve_image_push:
          type: approval
          requires:
            - build
      - build_and_push_image:
          filters:
            branches:
              only:
                - main
          requires:
            - approve_image_push

jobs:
  build:
    working_directory: ~/apa3-api
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout
      - run:
          # Restore
          name: Restore Dependencies and Tools
          command: ls -a . & dotnet restore APA3/APA3.csproj
      - run:
          # Build Project
          name: Build Project
          command: dotnet build --no-restore APA3/APA3.csproj
      
  build_and_push_image:
    executor: gcp-gcr/default
    steps:
      - checkout
      - gcp-gcr/gcr-auth
      - gcp-gcr/build-image:
          image: apa3-api
          no_output_timeout: 20m
          registry-url: us.gcr.io
          tag: 0.1.${CIRCLE_BUILD_NUM}
      - gcp-gcr/push-image:
          digest-path: /tmp/digest.txt
          image: apa3-api
          registry-url: us.gcr.io
          tag: 0.1.${CIRCLE_BUILD_NUM}
      - gcp-gcr/tag-image:
          image: apa3-api
          registry-url: us.gcr.io
          source-tag: 0.1.${CIRCLE_BUILD_NUM}
          target-tag: latest
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"